remote_theme: pages-themes/midnight
# remote_theme: pages-themes/minimal

# Site settings
title: プロフィール
description: プロフィール
baseurl: ""
url: "https://tomoya-kamaji.github.io"

# Theme customization
show_excerpts: true
show_sidebar: true

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/