theme: jekyll-theme-slate

# Site settings
title: プロフィール
description: プロフィール
baseurl: "/tomoya-kamaji"
url: "https://tomoya-kamaji.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/