remote_theme: pages-themes/slate@v0.2.0

# Site settings
title: プロフィール
description: プロフィール
baseurl: "/tomoya-kamaji"
url: "https://tomoya-kamaji.github.io"
show_downloads: false

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/